# Generated by Django 5.0.6 on 2024-05-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_login_db_singup_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singup_db',
            name='Confirm',
        ),
    ]
