# Generated by Django 5.0.6 on 2024-06-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_delete_singup_db_login_db_conform_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_db',
            name='conform_password',
        ),
    ]
